export const ipcChannels = {
  database: {
    exportBackup: 'database:export-backup',
    restoreBackup: 'database:restore-backup',
  },
  app: {
    getInfo: 'app:get-info',
    exportDiagnostics: 'app:export-diagnostics',
    rendererReady: 'app:renderer-ready',
    splashReady: 'app:splash-ready',
  },
  library: {
    getStats: 'library:get-stats',
    selectRoot: 'library:select-root',
    getRoots: 'library:get-roots',
    startScan: 'library:start-scan',
    cancelScan: 'library:cancel-scan',
    getScanStatus: 'library:get-scan-status',
    getTracks: 'library:get-tracks',
    getTrackPage: 'library:get-track-page',
    getAlbumDetail: 'library:get-album-detail',
    scanProgress: 'library:scan-progress',
    changed: 'library:changed',
  },
  smartPlaylists: {
    list: 'smart-playlists:list',
    listTrackCounts: 'smart-playlists:list-track-counts',
    getDetail: 'smart-playlists:get-detail',
    create: 'smart-playlists:create',
    createFromQuery: 'smart-playlists:create-from-query',
    createRecentFrequent: 'smart-playlists:create-recent-frequent',
    updateRecentFrequentDays: 'smart-playlists:update-recent-frequent-days',
    rename: 'smart-playlists:rename',
    updateViewMode: 'smart-playlists:update-view-mode',
    delete: 'smart-playlists:delete',
    reorder: 'smart-playlists:reorder',
  },
  playlists: {
    list: 'playlists:list',
    listTrackCounts: 'playlists:list-track-counts',
    listSidebarItems: 'playlists:list-sidebar-items',
    getDetail: 'playlists:get-detail',
    create: 'playlists:create',
    rename: 'playlists:rename',
    updateViewMode: 'playlists:update-view-mode',
    delete: 'playlists:delete',
    addTracks: 'playlists:add-tracks',
    reorderSidebarItems: 'playlists:reorder-sidebar-items',
  },
  lyrics: {
    getByTrackId: 'lyrics:get-by-track-id',
  },
  playback: {
    nativeAvailability: 'playback:native-availability',
    nativeCommand: 'playback:native-command',
    nativeEvent: 'playback:native-event',
    getAudioUrl: 'playback:get-audio-url',
    getRandomTrack: 'playback:get-random-track',
    getRandomAlbumTracks: 'playback:get-random-album-tracks',
    getAlbumTracks: 'playback:get-album-tracks',
    recordEffectivePlay: 'playback:record-effective-play',
    acquireReadLease: 'playback:acquire-read-lease',
    releaseReadLease: 'playback:release-read-lease',
  },
  systemMedia: {
    updateThumbarState: 'system-media:update-thumbar-state',
    command: 'system-media:command',
  },
  archive: {
    getListeningHeatmap: 'archive:get-listening-heatmap',
    getDailyListeningDetail: 'archive:get-daily-listening-detail',
    getDailyAlbumStats: 'archive:get-daily-album-stats',
    getAnnualListeningInsights: 'archive:get-annual-listening-insights',
    getListeningRanking: 'archive:get-listening-ranking',
    getListeningGenreSpectrum: 'archive:get-listening-genre-spectrum',
    resetPlayStats: 'archive:reset-play-stats',
  },
  metadata: {
    refreshTrack: 'metadata:refresh-track',
    refreshTracks: 'metadata:refresh-tracks',
    refreshLyricsMissing: 'metadata:refresh-lyrics-missing',
    getRefreshStatus: 'metadata:get-refresh-status',
    listRefreshFailures: 'metadata:list-refresh-failures',
    clearRefreshFailures: 'metadata:clear-refresh-failures',
    getTrackMetadata: 'metadata:get-track-metadata',
    getTrackEditState: 'metadata:get-track-edit-state',
    updateTrackMetadata: 'metadata:update-track-metadata',
    refreshProgress: 'metadata:refresh-progress',
    trackEditStateChanged: 'metadata:track-edit-state-changed',
  },
  window: {
    control: 'window:control',
    getMaximized: 'window:get-maximized',
    maximizedChanged: 'window:maximized-changed',
  },
} as const
