import type { DomainIpcInvokeChannel } from './ipcPayloadValidation'

/** Representative payloads for every non-void channel; tests assert coverage. */
export const validIpcPayloads: Partial<Record<DomainIpcInvokeChannel, unknown>> = {
  'library:start-scan': { rootId: 1 },
  'library:cancel-scan': { jobId: 1 },
  'library:get-scan-status': { jobId: 1 },
  'library:get-track-page': { cursor: 'snapshot:cursor', limit: 1000, refresh: true },
  'library:get-album-detail': { albumArtist: 'Artist', albumTitle: 'Album' },
  'smart-playlists:get-detail': { id: 1 },
  'smart-playlists:create': {
    name: 'Name',
    rule: { expression: { type: 'predicate', field: 'genre', operator: 'has', value: 'Ambient' } },
  },
  'smart-playlists:create-from-query': { query: 'genre:Ambient' },
  'smart-playlists:create-recent-added': { days: 30 },
  'smart-playlists:update-recent-added-days': { id: 1, days: 30 },
  'smart-playlists:rename': { id: 1, name: 'Name' },
  'smart-playlists:update-view-mode': { id: 1, viewMode: 'cover' },
  'smart-playlists:delete': { id: 1 },
  'smart-playlists:reorder': { ids: [1, 2] },
  'playlists:get-detail': { id: 1 },
  'playlists:rename': { id: 1, name: 'Name' },
  'playlists:update-view-mode': { id: 1, viewMode: 'flat' },
  'playlists:delete': { id: 1 },
  'playlists:add-tracks': { id: 1, trackIds: [1, 2] },
  'playlists:reorder-sidebar-items': {
    items: [
      { kind: 'playlist', id: 1 },
      { kind: 'smart', id: 2 },
    ],
  },
  'lyrics:get-by-track-id': { trackId: 1 },
  'playback:get-audio-url': { trackId: 1 },
  'playback:spectrum-subscribe': {
    subscriptionId: 0,
    revision: 1,
    enabled: true,
    trackId: null,
    currentTime: 0,
    isPlaying: false,
  },
  'playback:native-command': { action: 'start', session: 0, trackId: 1, volume: 0.5, muted: false },
  'playback:get-random-track': { excludeTrackId: 1 },
  'playback:get-random-album-tracks': {
    excludeAlbumKey: { albumArtist: 'Artist', album: 'Album' },
  },
  'playback:get-album-tracks': { albumKey: { albumArtist: 'Artist', album: 'Album' } },
  'playback:record-effective-play': {
    trackId: 1,
    sessionId: 'session',
    playedAtIso: '2026-10-04T12:00:00Z',
  },
  'playback:acquire-read-lease': { trackId: 1 },
  'playback:release-read-lease': { leaseId: 'lease' },
  'archive:get-listening-heatmap': { year: 2026 },
  'archive:get-daily-listening-detail': { date: '2026-10-04' },
  'archive:get-daily-album-stats': { date: '2026-02-30' },
  'archive:get-annual-listening-insights': { year: 2026 },
  'archive:get-listening-ranking': { range: 'month', target: 'album', year: 2026, month: 10 },
  'archive:get-listening-genre-spectrum': { year: 2026 },
  'metadata:refresh-track': { trackId: 1 },
  'metadata:refresh-tracks': { trackIds: [1, 2] },
  'metadata:refresh-lyrics-missing': { limit: 100 },
  'metadata:get-refresh-status': { jobId: 1 },
  'metadata:list-refresh-failures': { limit: 100 },
  'metadata:get-track-metadata': { trackId: 1 },
  'metadata:get-track-edit-state': { trackId: 1 },
  'metadata:update-track-metadata': {
    trackId: 1,
    title: 'Title',
    artistDisplay: null,
    albumTitle: 'Album',
    albumArtistDisplay: 'Artist',
    genreDisplay: 'Genre',
    year: 2026,
    releaseDate: '2026-10',
  },
  'window:control': { action: 'close' },
}
